# Generated by Django 5.1.3 on 2025-01-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='user/default_user.png', null=True, upload_to='images/user/', verbose_name='Фото пользователя'),
        ),
    ]
