# Generated by Django 5.1.3 on 2025-01-05 01:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ресторан/фастфуд/бар', max_length=50, verbose_name='Категория заведения')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Ссылочное поле(заполняется автоматически)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название заведения')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес заведения')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Ссылочное поле(заполняется автоматически)')),
                ('category_id', models.ForeignKey(blank=True, help_text='Выберите категорию заведения', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.categories', verbose_name='Поле для связи с категорией заведения')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
            },
        ),
        migrations.CreateModel(
            name='PlacePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, unique=True, upload_to='images', verbose_name='Вставьте фото заведения')),
                ('place_id', models.ForeignKey(help_text='Выберите заведение', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reviews.places', verbose_name='Поле для связи с заведением')),
            ],
            options={
                'verbose_name': 'Фотографии заведения',
                'verbose_name_plural': 'Фотографии заведений',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.CharField(help_text='Введите комментарий', max_length=200, verbose_name='Комментарий')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь оставивший комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'content_type', 'object_id', 'text'), name='unique_comment')],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(help_text='Введите вопрос', max_length=200, verbose_name='Вопрос по заведению')),
                ('place_id', models.ForeignKey(help_text='Выберите заведение', on_delete=django.db.models.deletion.CASCADE, to='reviews.places', verbose_name='Поле для связи с заведением')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь оставивший оценку')),
            ],
            options={
                'verbose_name': 'Вопрос к заведению',
                'verbose_name_plural': 'Вопросы к заведениям',
                'constraints': [models.UniqueConstraint(fields=('place_id', 'user_id', 'text'), name='unique_question')],
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(blank=True, help_text='Напишите о заведении', max_length=500, null=True, verbose_name='Письменный отзыв пользователя')),
                ('price', models.PositiveSmallIntegerField(default=3, help_text='Выберите оценку по критерию цена', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Поле для оценки цены в заведении')),
                ('service', models.PositiveSmallIntegerField(default=3, help_text='Выберите оценку по критерию обслуживания', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Поле для оценки обслуживания в заведении')),
                ('interior', models.PositiveSmallIntegerField(default=3, help_text='Выберите оценку по критерию интерьер', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Поле для оценки инерьера в заведении')),
                ('place_id', models.ForeignKey(help_text='Выберите заведение', on_delete=django.db.models.deletion.CASCADE, to='reviews.places', verbose_name='Поле для связи с заведением')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь оставивший оценку')),
            ],
            options={
                'verbose_name': 'Отзыв заведения',
                'verbose_name_plural': 'Отзывы заведений',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'place_id', 'text'), name='unique_review')],
            },
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('vote_type', models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь оставивший комментарий')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'content_type', 'object_id'), name='unique_vote')],
            },
        ),
    ]
