# Generated by Django 5.1.3 on 2025-01-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='О заведении'),
        ),
    ]
