# Generated by Django 5.1.3 on 2025-01-07 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_places_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='category_id',
            field=models.ForeignKey(blank=True, help_text='Выберите категорию заведения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='reviews.categories', verbose_name='Поле для связи с категорией заведения'),
        ),
    ]
